# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arraytool.ui'
#
# Created: Sat Mar 18 12:37:21 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtGui.QScrollArea(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-61, -271, 770, 756))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.linescanx = QtGui.QLineEdit(self.groupBox_3)
        self.linescanx.setObjectName("linescanx")
        self.gridLayout_5.addWidget(self.linescanx, 2, 1, 1, 1)
        self.linescany = QtGui.QLineEdit(self.groupBox_3)
        self.linescany.setObjectName("linescany")
        self.gridLayout_5.addWidget(self.linescany, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.linescanp = QtGui.QLineEdit(self.groupBox_3)
        self.linescanp.setObjectName("linescanp")
        self.gridLayout_5.addWidget(self.linescanp, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.linescant = QtGui.QLineEdit(self.groupBox_3)
        self.linescant.setObjectName("linescant")
        self.gridLayout_5.addWidget(self.linescant, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupX = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupX.setCheckable(True)
        self.groupX.setChecked(False)
        self.groupX.setObjectName("groupX")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupX)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtGui.QLabel(self.groupX)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupX)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1)
        self.comboX = QtGui.QComboBox(self.groupX)
        self.comboX.setObjectName("comboX")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.gridLayout_6.addWidget(self.comboX, 0, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.groupX)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_6.addWidget(self.radioButton, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtGui.QLabel(self.groupX)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.linenoeX = QtGui.QLineEdit(self.groupX)
        self.linenoeX.setObjectName("linenoeX")
        self.gridLayout_6.addWidget(self.linenoeX, 1, 1, 1, 1)
        self.linebwX = QtGui.QLineEdit(self.groupX)
        self.linebwX.setObjectName("linebwX")
        self.gridLayout_6.addWidget(self.linebwX, 2, 1, 1, 1)
        self.lineslrX = QtGui.QLineEdit(self.groupX)
        self.lineslrX.setObjectName("lineslrX")
        self.gridLayout_6.addWidget(self.lineslrX, 3, 1, 1, 1)
        self.linembar = QtGui.QLineEdit(self.groupX)
        self.linembar.setObjectName("linembar")
        self.gridLayout_6.addWidget(self.linembar, 4, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupX)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_6.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupX, 3, 0, 1, 1)
        self.groupRho = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupRho.setCheckable(True)
        self.groupRho.setChecked(False)
        self.groupRho.setObjectName("groupRho")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupRho)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_5 = QtGui.QRadioButton(self.groupRho)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_8.addWidget(self.radioButton_5, 2, 0, 1, 1)
        self.radioButton_6 = QtGui.QRadioButton(self.groupRho)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_8.addWidget(self.radioButton_6, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_15 = QtGui.QLabel(self.groupRho)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupRho)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupRho)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 4, 0, 1, 1)
        self.linenoeR = QtGui.QLineEdit(self.groupRho)
        self.linenoeR.setObjectName("linenoeR")
        self.gridLayout_8.addWidget(self.linenoeR, 1, 1, 1, 1)
        self.linebwR = QtGui.QLineEdit(self.groupRho)
        self.linebwR.setObjectName("linebwR")
        self.gridLayout_8.addWidget(self.linebwR, 2, 1, 1, 1)
        self.lineslrR = QtGui.QLineEdit(self.groupRho)
        self.lineslrR.setObjectName("lineslrR")
        self.gridLayout_8.addWidget(self.lineslrR, 3, 1, 1, 1)
        self.linepbar = QtGui.QLineEdit(self.groupRho)
        self.linepbar.setObjectName("linepbar")
        self.gridLayout_8.addWidget(self.linepbar, 4, 1, 1, 1)
        self.comboRho = QtGui.QComboBox(self.groupRho)
        self.comboRho.setObjectName("comboRho")
        self.comboRho.addItem("")
        self.comboRho.addItem("")
        self.comboRho.addItem("")
        self.comboRho.addItem("")
        self.gridLayout_8.addWidget(self.comboRho, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupRho, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.linefreq = QtGui.QLineEdit(self.groupBox_2)
        self.linefreq.setObjectName("linefreq")
        self.gridLayout.addWidget(self.linefreq, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.linea = QtGui.QLineEdit(self.groupBox_2)
        self.linea.setObjectName("linea")
        self.gridLayout.addWidget(self.linea, 1, 1, 1, 1)
        self.lineb = QtGui.QLineEdit(self.groupBox_2)
        self.lineb.setObjectName("lineb")
        self.gridLayout.addWidget(self.lineb, 2, 1, 1, 1)
        self.linegamma = QtGui.QLineEdit(self.groupBox_2)
        self.linegamma.setObjectName("linegamma")
        self.gridLayout.addWidget(self.linegamma, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupY = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupY.setCheckable(True)
        self.groupY.setChecked(False)
        self.groupY.setObjectName("groupY")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupY)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_3 = QtGui.QRadioButton(self.groupY)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_7.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.groupY)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_7.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtGui.QLabel(self.groupY)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupY)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupY)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 4, 0, 1, 1)
        self.linenoeY = QtGui.QLineEdit(self.groupY)
        self.linenoeY.setObjectName("linenoeY")
        self.gridLayout_7.addWidget(self.linenoeY, 1, 1, 1, 1)
        self.linebwY = QtGui.QLineEdit(self.groupY)
        self.linebwY.setObjectName("linebwY")
        self.gridLayout_7.addWidget(self.linebwY, 2, 1, 1, 1)
        self.lineslrY = QtGui.QLineEdit(self.groupY)
        self.lineslrY.setObjectName("lineslrY")
        self.gridLayout_7.addWidget(self.lineslrY, 3, 1, 1, 1)
        self.linenbar = QtGui.QLineEdit(self.groupY)
        self.linenbar.setObjectName("linenbar")
        self.gridLayout_7.addWidget(self.linenbar, 4, 1, 1, 1)
        self.comboY = QtGui.QComboBox(self.groupY)
        self.comboY.setObjectName("comboY")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.gridLayout_7.addWidget(self.comboY, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupY, 3, 1, 1, 1)
        self.groupQuant = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupQuant.setCheckable(True)
        self.groupQuant.setChecked(False)
        self.groupQuant.setObjectName("groupQuant")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupQuant)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.linescanfreq = QtGui.QLineEdit(self.groupQuant)
        self.linescanfreq.setObjectName("linescanfreq")
        self.gridLayout_9.addWidget(self.linescanfreq, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtGui.QLabel(self.groupQuant)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupQuant)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineabits = QtGui.QLineEdit(self.groupQuant)
        self.lineabits.setObjectName("lineabits")
        self.gridLayout_9.addWidget(self.lineabits, 1, 1, 1, 1)
        self.linepbits = QtGui.QLineEdit(self.groupQuant)
        self.linepbits.setObjectName("linepbits")
        self.gridLayout_9.addWidget(self.linepbits, 2, 1, 1, 1)
        self.linedblimit = QtGui.QLineEdit(self.groupQuant)
        self.linedblimit.setObjectName("linedblimit")
        self.gridLayout_9.addWidget(self.linedblimit, 3, 1, 1, 1)
        self.pushplotspec = QtGui.QPushButton(self.groupQuant)
        self.pushplotspec.setObjectName("pushplotspec")
        self.gridLayout_9.addWidget(self.pushplotspec, 4, 0, 1, 2)
        self.label_21 = QtGui.QLabel(self.groupQuant)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupQuant)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupQuant, 4, 1, 1, 1)
        self.groupOperations = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupOperations.setObjectName("groupOperations")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupOperations)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_10.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.comboOperations = QtGui.QComboBox(self.groupOperations)
        self.comboOperations.setObjectName("comboOperations")
        self.comboOperations.addItem("")
        self.comboOperations.addItem("")
        self.comboOperations.addItem("")
        self.comboOperations.addItem("")
        self.comboOperations.addItem("")
        self.gridLayout_10.addWidget(self.comboOperations, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupOperations, 0, 0, 1, 1)
        self.groupGrating = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupGrating.setCheckable(True)
        self.groupGrating.setObjectName("groupGrating")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupGrating)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboGrating = QtGui.QComboBox(self.groupGrating)
        self.comboGrating.setObjectName("comboGrating")
        self.comboGrating.addItem("")
        self.comboGrating.addItem("")
        self.comboGrating.addItem("")
        self.comboGrating.addItem("")
        self.verticalLayout_6.addWidget(self.comboGrating)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupGrating, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.GAtab = QtGui.QWidget()
        self.GAtab.setObjectName("GAtab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.GAtab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_AGL = QtGui.QVBoxLayout()
        self.verticalLayout_AGL.setObjectName("verticalLayout_AGL")
        self.verticalLayout_8.addLayout(self.verticalLayout_AGL)
        self.tabWidget.addTab(self.GAtab, "")
        self.cutstab = QtGui.QWidget()
        self.cutstab.setObjectName("cutstab")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.cutstab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2D = QtGui.QVBoxLayout()
        self.verticalLayout_2D.setObjectName("verticalLayout_2D")
        self.verticalLayout_10.addLayout(self.verticalLayout_2D)
        self.tabWidget.addTab(self.cutstab, "")
        self.contourtab = QtGui.QWidget()
        self.contourtab.setObjectName("contourtab")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.contourtab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget_2 = QtGui.QTabWidget(self.contourtab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.verticalLayout_11.addWidget(self.tabWidget_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.contourtab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tabWidget_3 = QtGui.QTabWidget(self.tab)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.verticalLayout_15.addWidget(self.tabWidget_3)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab, "")
        self.log = QtGui.QWidget()
        self.log.setObjectName("log")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.log)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_Log = QtGui.QVBoxLayout()
        self.verticalLayout_Log.setObjectName("verticalLayout_Log")
        self.verticalLayout_14.addLayout(self.verticalLayout_Log)
        self.tabWidget.addTab(self.log, "")
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(22, 22))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRun = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/categories/applications-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon)
        self.actionRun.setStatusTip("")
        self.actionRun.setObjectName("actionRun")
        self.action_New = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon1)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon2)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon3)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon4)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_Quit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/system-log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon5)
        self.action_Quit.setObjectName("action_Quit")
        self.actionArraytool_Help = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/apps/help-browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArraytool_Help.setIcon(icon6)
        self.actionArraytool_Help.setObjectName("actionArraytool_Help")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClear_Data = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/22x22/actions/edit-clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_Data.setIcon(icon7)
        self.actionClear_Data.setObjectName("actionClear_Data")
        self.actionArray_Grating_Lobes = QtGui.QAction(MainWindow)
        self.actionArray_Grating_Lobes.setCheckable(True)
        self.actionArray_Grating_Lobes.setObjectName("actionArray_Grating_Lobes")
        self.action2D_Pattern_Vuts = QtGui.QAction(MainWindow)
        self.action2D_Pattern_Vuts.setCheckable(True)
        self.action2D_Pattern_Vuts.setObjectName("action2D_Pattern_Vuts")
        self.actionTheta_Phi_Plots = QtGui.QAction(MainWindow)
        self.actionTheta_Phi_Plots.setCheckable(True)
        self.actionTheta_Phi_Plots.setObjectName("actionTheta_Phi_Plots")
        self.actionUV_Plots = QtGui.QAction(MainWindow)
        self.actionUV_Plots.setCheckable(True)
        self.actionUV_Plots.setObjectName("actionUV_Plots")
        self.actionMisc = QtGui.QAction(MainWindow)
        self.actionMisc.setCheckable(True)
        self.actionMisc.setObjectName("actionMisc")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionClear_Data)
        self.menu_Help.addAction(self.actionArraytool_Help)
        self.menu_Help.addAction(self.actionAbout)
        self.menuView.addAction(self.actionArray_Grating_Lobes)
        self.menuView.addAction(self.action2D_Pattern_Vuts)
        self.menuView.addAction(self.actionTheta_Phi_Plots)
        self.menuView.addAction(self.actionUV_Plots)
        self.menuView.addAction(self.actionMisc)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addAction(self.actionClear_Data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionArraytool_Help)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Quit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QObject.connect(self.groupRho, QtCore.SIGNAL("clicked(bool)"), self.groupX.setDisabled)
        QtCore.QObject.connect(self.groupRho, QtCore.SIGNAL("clicked(bool)"), self.groupY.setDisabled)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboOperations, self.comboGrating)
        MainWindow.setTabOrder(self.comboGrating, self.linefreq)
        MainWindow.setTabOrder(self.linefreq, self.linea)
        MainWindow.setTabOrder(self.linea, self.lineb)
        MainWindow.setTabOrder(self.lineb, self.linegamma)
        MainWindow.setTabOrder(self.linegamma, self.linescant)
        MainWindow.setTabOrder(self.linescant, self.linescanp)
        MainWindow.setTabOrder(self.linescanp, self.linescanx)
        MainWindow.setTabOrder(self.linescanx, self.linescany)
        MainWindow.setTabOrder(self.linescany, self.groupX)
        MainWindow.setTabOrder(self.groupX, self.comboX)
        MainWindow.setTabOrder(self.comboX, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.linenoeX)
        MainWindow.setTabOrder(self.linenoeX, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.linebwX)
        MainWindow.setTabOrder(self.linebwX, self.lineslrX)
        MainWindow.setTabOrder(self.lineslrX, self.linembar)
        MainWindow.setTabOrder(self.linembar, self.groupY)
        MainWindow.setTabOrder(self.groupY, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.linenoeY)
        MainWindow.setTabOrder(self.linenoeY, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.linebwY)
        MainWindow.setTabOrder(self.linebwY, self.lineslrY)
        MainWindow.setTabOrder(self.lineslrY, self.linenbar)
        MainWindow.setTabOrder(self.linenbar, self.groupRho)
        MainWindow.setTabOrder(self.groupRho, self.comboRho)
        MainWindow.setTabOrder(self.comboRho, self.radioButton_6)
        MainWindow.setTabOrder(self.radioButton_6, self.linenoeR)
        MainWindow.setTabOrder(self.linenoeR, self.radioButton_5)
        MainWindow.setTabOrder(self.radioButton_5, self.linebwR)
        MainWindow.setTabOrder(self.linebwR, self.lineslrR)
        MainWindow.setTabOrder(self.lineslrR, self.linepbar)
        MainWindow.setTabOrder(self.linepbar, self.groupQuant)
        MainWindow.setTabOrder(self.groupQuant, self.linescanfreq)
        MainWindow.setTabOrder(self.linescanfreq, self.lineabits)
        MainWindow.setTabOrder(self.lineabits, self.linepbits)
        MainWindow.setTabOrder(self.linepbits, self.linedblimit)
        MainWindow.setTabOrder(self.linedblimit, self.pushplotspec)
        MainWindow.setTabOrder(self.pushplotspec, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.scrollArea)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Arraytool GUI Application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Scan Angles", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanx.setToolTip(QtGui.QApplication.translate("MainWindow", "See the Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanx.setStatusTip(QtGui.QApplication.translate("MainWindow", "See the Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanx.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.linescany.setToolTip(QtGui.QApplication.translate("MainWindow", "See the Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.linescany.setStatusTip(QtGui.QApplication.translate("MainWindow", "See the Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.linescany.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "scan phi (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "scan x (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanp.setToolTip(QtGui.QApplication.translate("MainWindow", "Phi Component of Scan Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Phi Component of Scan Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanp.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "scan theta (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "scan y (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.linescant.setToolTip(QtGui.QApplication.translate("MainWindow", "Theta Component of Scan Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linescant.setStatusTip(QtGui.QApplication.translate("MainWindow", "Theta Component of Scan Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linescant.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupX.setToolTip(QtGui.QApplication.translate("MainWindow", "Array Distribution along X", None, QtGui.QApplication.UnicodeUTF8))
        self.groupX.setStatusTip(QtGui.QApplication.translate("MainWindow", "Array Distribution along X", None, QtGui.QApplication.UnicodeUTF8))
        self.groupX.setTitle(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "SLR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "m-bar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setToolTip(QtGui.QApplication.translate("MainWindow", "Ax(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ax(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(0, QtGui.QApplication.translate("MainWindow", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(1, QtGui.QApplication.translate("MainWindow", "Binomial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(2, QtGui.QApplication.translate("MainWindow", "Dolph-Chebyshev", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(3, QtGui.QApplication.translate("MainWindow", "Taylor One Paramter", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(4, QtGui.QApplication.translate("MainWindow", "Taylor n-bar (Villeneuve)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(5, QtGui.QApplication.translate("MainWindow", "Uniform Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(6, QtGui.QApplication.translate("MainWindow", "Triangular Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.comboX.setItemText(7, QtGui.QApplication.translate("MainWindow", "Bayliss n-bar Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "No. of Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeX.setToolTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along X (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeX.setStatusTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along X (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwX.setToolTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=0 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwX.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=0 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrX.setToolTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along X", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrX.setStatusTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along X", None, QtGui.QApplication.UnicodeUTF8))
        self.linembar.setToolTip(QtGui.QApplication.translate("MainWindow", "Taylor\'s n-bar Paramter along X", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Beamwidth (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupRho.setToolTip(QtGui.QApplication.translate("MainWindow", "Array Distribution along Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.groupRho.setTitle(QtGui.QApplication.translate("MainWindow", "Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "Beamwidth (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "No. of Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "SLR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "p-bar", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeR.setToolTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along Rho (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeR.setStatusTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along Rho (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwR.setToolTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=0 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwR.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=0 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrR.setToolTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrR.setStatusTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.linepbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Taylor\'s n-bar Paramter along Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.linepbar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Taylor\'s n-bar Paramter along Rho", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRho.setToolTip(QtGui.QApplication.translate("MainWindow", "Arho(rho)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRho.setItemText(0, QtGui.QApplication.translate("MainWindow", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRho.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hansen One Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRho.setItemText(2, QtGui.QApplication.translate("MainWindow", "Taylor Circular n-bar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRho.setItemText(3, QtGui.QApplication.translate("MainWindow", "Circular Bayliss", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Frequency && Array Lattice Paramters ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "a (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "b (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.linefreq.setToolTip(QtGui.QApplication.translate("MainWindow", "Frequency of Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.linefreq.setStatusTip(QtGui.QApplication.translate("MainWindow", "Frequency of Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.linefreq.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Frequency (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "gamma (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.linea.setToolTip(QtGui.QApplication.translate("MainWindow", "Uniform Separation along X Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.linea.setStatusTip(QtGui.QApplication.translate("MainWindow", "Uniform Separation along X Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.linea.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.lineb.setToolTip(QtGui.QApplication.translate("MainWindow", "Uniform Separation along Y Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.lineb.setStatusTip(QtGui.QApplication.translate("MainWindow", "Uniform Separation along Y Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.lineb.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.linegamma.setToolTip(QtGui.QApplication.translate("MainWindow", "Array Lattice Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linegamma.setStatusTip(QtGui.QApplication.translate("MainWindow", "Array Lattice Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.linegamma.setText(QtGui.QApplication.translate("MainWindow", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.groupY.setToolTip(QtGui.QApplication.translate("MainWindow", "Array Distribution along Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupY.setTitle(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Beamwidth (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "No. of Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "SLR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "n-bar", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeY.setToolTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along Y (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.linenoeY.setStatusTip(QtGui.QApplication.translate("MainWindow", "No. of Elements along Y (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwY.setToolTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=90 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.linebwY.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beamwidth along Phi=90 Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrY.setToolTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lineslrY.setStatusTip(QtGui.QApplication.translate("MainWindow", "Side Lobe Ratio along Y", None, QtGui.QApplication.UnicodeUTF8))
        self.linenbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Taylor\'s n-bar Paramter along Y", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(0, QtGui.QApplication.translate("MainWindow", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(1, QtGui.QApplication.translate("MainWindow", "Binomial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(2, QtGui.QApplication.translate("MainWindow", "Dolph-Chebyshev", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(3, QtGui.QApplication.translate("MainWindow", "Taylor One Paramter", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(4, QtGui.QApplication.translate("MainWindow", "Taylor n-bar (Villeneuve)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(5, QtGui.QApplication.translate("MainWindow", "Uniform Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(6, QtGui.QApplication.translate("MainWindow", "Triangular Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.comboY.setItemText(7, QtGui.QApplication.translate("MainWindow", "Bayliss n-bar Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.groupQuant.setTitle(QtGui.QApplication.translate("MainWindow", "Quantization, etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanfreq.setToolTip(QtGui.QApplication.translate("MainWindow", "Frequency at which Phase Shifters are Tuned", None, QtGui.QApplication.UnicodeUTF8))
        self.linescanfreq.setStatusTip(QtGui.QApplication.translate("MainWindow", "Frequency at which Phase Shifters are Tuned", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Scan Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "dB Lower limit", None, QtGui.QApplication.UnicodeUTF8))
        self.lineabits.setToolTip(QtGui.QApplication.translate("MainWindow", "Amplitude Quantization bits", None, QtGui.QApplication.UnicodeUTF8))
        self.lineabits.setStatusTip(QtGui.QApplication.translate("MainWindow", "Amplitude Quantization bits", None, QtGui.QApplication.UnicodeUTF8))
        self.linepbits.setToolTip(QtGui.QApplication.translate("MainWindow", "Phase Quantization bits", None, QtGui.QApplication.UnicodeUTF8))
        self.linepbits.setStatusTip(QtGui.QApplication.translate("MainWindow", "Phase Quantization bits", None, QtGui.QApplication.UnicodeUTF8))
        self.linedblimit.setToolTip(QtGui.QApplication.translate("MainWindow", "dB Lower Limit for Plotting Purpose", None, QtGui.QApplication.UnicodeUTF8))
        self.linedblimit.setStatusTip(QtGui.QApplication.translate("MainWindow", "dB Lower Limit for Plotting Purpose", None, QtGui.QApplication.UnicodeUTF8))
        self.pushplotspec.setToolTip(QtGui.QApplication.translate("MainWindow", "Theta Cut, Phi Cut, Theta Resolution, Phi Resolution, 2D Pattern, 3D Pattern, etc", None, QtGui.QApplication.UnicodeUTF8))
        self.pushplotspec.setStatusTip(QtGui.QApplication.translate("MainWindow", "Theta Cut, Phi Cut, Theta Resolution, Phi Resolution, 2D Pattern, 3D Pattern, etc", None, QtGui.QApplication.UnicodeUTF8))
        self.pushplotspec.setText(QtGui.QApplication.translate("MainWindow", "Plot Specifications", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Amplitude bits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Phase bits", None, QtGui.QApplication.UnicodeUTF8))
        self.groupOperations.setTitle(QtGui.QApplication.translate("MainWindow", "Choose One of the Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose one of the Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose one of the Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setItemText(0, QtGui.QApplication.translate("MainWindow", "Grating Lobe Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setItemText(1, QtGui.QApplication.translate("MainWindow", "Typical Array Analysis & Synthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setItemText(2, QtGui.QApplication.translate("MainWindow", "User Defined Array Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setItemText(3, QtGui.QApplication.translate("MainWindow", "Shaped Beam Synthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOperations.setItemText(4, QtGui.QApplication.translate("MainWindow", "Mutual Coupling Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupGrating.setTitle(QtGui.QApplication.translate("MainWindow", "Grating Lobe Analysis Options", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose among Different Scan Sector Options", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose among Different Scan Sector Options", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setItemText(0, QtGui.QApplication.translate("MainWindow", "Conical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setItemText(1, QtGui.QApplication.translate("MainWindow", "Rectangular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setItemText(2, QtGui.QApplication.translate("MainWindow", "Knittel Side", None, QtGui.QApplication.UnicodeUTF8))
        self.comboGrating.setItemText(3, QtGui.QApplication.translate("MainWindow", "Knittel Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Array Distrbution Type & Specifications", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GAtab), QtGui.QApplication.translate("MainWindow", "Array && Grating Lobes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cutstab), QtGui.QApplication.translate("MainWindow", "2D Pattern Cuts", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Contour Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "3D Polar Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "3D Surf Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contourtab), QtGui.QApplication.translate("MainWindow", "Theta Phi Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Contour Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "3D Surf Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "UV Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setToolTip(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArraytool_Help.setText(QtGui.QApplication.translate("MainWindow", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArraytool_Help.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Data.setText(QtGui.QApplication.translate("MainWindow", "Clear &Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Data.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArray_Grating_Lobes.setText(QtGui.QApplication.translate("MainWindow", "Array && Grating Lobes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArray_Grating_Lobes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.action2D_Pattern_Vuts.setText(QtGui.QApplication.translate("MainWindow", "2D Pattern Cuts", None, QtGui.QApplication.UnicodeUTF8))
        self.action2D_Pattern_Vuts.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta_Phi_Plots.setText(QtGui.QApplication.translate("MainWindow", "Theta Phi Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta_Phi_Plots.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUV_Plots.setText(QtGui.QApplication.translate("MainWindow", "UV Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUV_Plots.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMisc.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMisc.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+5", None, QtGui.QApplication.UnicodeUTF8))

import arraytool_rc
